sudo: required
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ros-dps-interest@amazon.com
services:
    - docker
before_install:
    - docker pull osrf/ros2:nightly 
    - docker run -dit -v "${TRAVIS_BUILD_DIR}:/shared"  --network host --name=osrf_ros2_nightly --privileged osrf/ros2:nightly /bin/bash
    - docker exec osrf_ros2_nightly /bin/bash -c "git config --global user.name nobody"
    - docker exec osrf_ros2_nightly /bin/bash -c "git config --global user.email noreply@osrfoundation.org"
script:
    - docker exec osrf_ros2_nightly /bin/bash -c "rosdep update && rosdep install --from-paths /shared --ignore-src -r -y"
    - docker exec osrf_ros2_nightly /bin/bash -c "source /opt/ros/dashing/setup.bash && cd /shared/ && colcon build --packages-up-to rmw_dps_cpp"
    - docker exec osrf_ros2_nightly /bin/bash -c "source /opt/ros/dashing/setup.bash && cd /shared/ && colcon test --packages-select rmw_dps_cpp"
    - docker exec osrf_ros2_nightly /bin/bash -c "source /opt/ros/dashing/setup.bash && cd /shared/ && colcon test-result --verbose"
